export interface FlyerTemplate {
  id: string;
  name: string;
  description: string;
  previewColor: string;
  bgColor: string;
  bgAccent: string;
  headerColor: string;
  headerText: string;
  bodyText: string;
  accentColor: string;
  accentText: string;
  ctaColor: string;
  ctaText: string;
  fontFamily: string;
  layout: "bold-split" | "centered-photo" | "framed-elegant" | "banner-action" | "editorial" | "minimal-clean" | "photo-dominant" | "retro-badge" | "diagonal-cut" | "sidebar-info";
}

export const flyerTemplates: FlyerTemplate[] = [
  // 1 — Bold Red Alert (from sample: high contrast red banner)
  {
    id: "bold-red",
    name: "Bold Red Alert",
    description: "High-impact red banner with large photo — maximum visibility",
    previewColor: "bg-red-600",
    bgColor: "#FFFFFF",
    bgAccent: "#FEE2E2",
    headerColor: "#DC2626",
    headerText: "#FFFFFF",
    bodyText: "#1A1A1A",
    accentColor: "#DC2626",
    accentText: "#FFFFFF",
    ctaColor: "#1A1A1A",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "bold-split",
  },
  // 2 — Warm & Friendly (from sample: warm orange/yellow tones like dog5-2)
  {
    id: "warm-orange",
    name: "Warm & Friendly",
    description: "Soft orange tones with rounded shapes — approachable and warm",
    previewColor: "bg-orange-400",
    bgColor: "#FFF7ED",
    bgAccent: "#FDBA74",
    headerColor: "#EA580C",
    headerText: "#FFFFFF",
    bodyText: "#431407",
    accentColor: "#F97316",
    accentText: "#FFFFFF",
    ctaColor: "#EA580C",
    ctaText: "#FFFFFF",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    layout: "centered-photo",
  },
  // 3 — Elegant Grey
  {
    id: "elegant-grey",
    name: "Elegant Grey",
    description: "Sophisticated dark frame with scalloped photo border",
    previewColor: "bg-gray-700",
    bgColor: "#F5F5F0",
    bgAccent: "#D4D4D4",
    headerColor: "#374151",
    headerText: "#F9FAFB",
    bodyText: "#1F2937",
    accentColor: "#374151",
    accentText: "#FFFFFF",
    ctaColor: "#059669",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "framed-elegant",
  },
  // 4 — Nature Green
  {
    id: "nature-green",
    name: "Nature Green",
    description: "Fresh green with bold banner — perfect for outdoor pets",
    previewColor: "bg-green-700",
    bgColor: "#FFFFFF",
    bgAccent: "#D1FAE5",
    headerColor: "#15803D",
    headerText: "#FFFFFF",
    bodyText: "#14532D",
    accentColor: "#22C55E",
    accentText: "#FFFFFF",
    ctaColor: "#15803D",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "banner-action",
  },
  // 5 — Purple Charm (from sample: purple background like dog4-2)
  {
    id: "purple-charm",
    name: "Purple Charm",
    description: "Playful purple gradient with centered layout — eye-catching",
    previewColor: "bg-purple-500",
    bgColor: "#C084FC",
    bgAccent: "#A855F7",
    headerColor: "#6B21A8",
    headerText: "#FFFFFF",
    bodyText: "#FFFFFF",
    accentColor: "#E9D5FF",
    accentText: "#6B21A8",
    ctaColor: "#6B21A8",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "editorial",
  },
  // 6 — Sunrise Gold
  {
    id: "sunrise-gold",
    name: "Sunrise Gold",
    description: "Warm golden tones with a sunny, hopeful feel",
    previewColor: "bg-amber-500",
    bgColor: "#FFFBEB",
    bgAccent: "#FDE68A",
    headerColor: "#B45309",
    headerText: "#FFFFFF",
    bodyText: "#78350F",
    accentColor: "#F59E0B",
    accentText: "#78350F",
    ctaColor: "#B45309",
    ctaText: "#FFFFFF",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    layout: "minimal-clean",
  },
  // 7 — Ocean Blue
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    description: "Calm deep blue with a trustworthy, professional look",
    previewColor: "bg-blue-600",
    bgColor: "#EFF6FF",
    bgAccent: "#BFDBFE",
    headerColor: "#1D4ED8",
    headerText: "#FFFFFF",
    bodyText: "#1E3A5F",
    accentColor: "#3B82F6",
    accentText: "#FFFFFF",
    ctaColor: "#1D4ED8",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "bold-split",
  },
  // 8 — Coral Sunset
  {
    id: "coral-sunset",
    name: "Coral Sunset",
    description: "Soft coral and pink tones — gentle and caring",
    previewColor: "bg-rose-400",
    bgColor: "#FFF1F2",
    bgAccent: "#FECDD3",
    headerColor: "#E11D48",
    headerText: "#FFFFFF",
    bodyText: "#881337",
    accentColor: "#FB7185",
    accentText: "#FFFFFF",
    ctaColor: "#E11D48",
    ctaText: "#FFFFFF",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    layout: "centered-photo",
  },
  // 9 — Midnight Dark
  {
    id: "midnight-dark",
    name: "Midnight Dark",
    description: "Dark dramatic design with high contrast text",
    previewColor: "bg-gray-900",
    bgColor: "#111827",
    bgAccent: "#1F2937",
    headerColor: "#F59E0B",
    headerText: "#111827",
    bodyText: "#F3F4F6",
    accentColor: "#F59E0B",
    accentText: "#111827",
    ctaColor: "#F59E0B",
    ctaText: "#111827",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "photo-dominant",
  },
  // 10 — Teal Fresh
  {
    id: "teal-fresh",
    name: "Teal Fresh",
    description: "Modern teal with clean lines and fresh energy",
    previewColor: "bg-teal-500",
    bgColor: "#F0FDFA",
    bgAccent: "#99F6E4",
    headerColor: "#0D9488",
    headerText: "#FFFFFF",
    bodyText: "#134E4A",
    accentColor: "#14B8A6",
    accentText: "#FFFFFF",
    ctaColor: "#0D9488",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "framed-elegant",
  },
  // 11 — Vintage Cream
  {
    id: "vintage-cream",
    name: "Vintage Cream",
    description: "Retro vintage style with warm cream and brown tones",
    previewColor: "bg-yellow-800",
    bgColor: "#FAF5EF",
    bgAccent: "#E8DCCC",
    headerColor: "#92400E",
    headerText: "#FAF5EF",
    bodyText: "#451A03",
    accentColor: "#B45309",
    accentText: "#FAF5EF",
    ctaColor: "#92400E",
    ctaText: "#FAF5EF",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    layout: "retro-badge",
  },
  // 12 — Electric Lime
  {
    id: "electric-lime",
    name: "Electric Lime",
    description: "Bold neon green for maximum street visibility",
    previewColor: "bg-lime-500",
    bgColor: "#F7FEE7",
    bgAccent: "#BEF264",
    headerColor: "#4D7C0F",
    headerText: "#FFFFFF",
    bodyText: "#365314",
    accentColor: "#84CC16",
    accentText: "#FFFFFF",
    ctaColor: "#4D7C0F",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "banner-action",
  },
  // 13 — Dusty Rose
  {
    id: "dusty-rose",
    name: "Dusty Rose",
    description: "Elegant blush pink with a delicate, caring aesthetic",
    previewColor: "bg-pink-300",
    bgColor: "#FDF2F8",
    bgAccent: "#FBCFE8",
    headerColor: "#BE185D",
    headerText: "#FFFFFF",
    bodyText: "#831843",
    accentColor: "#EC4899",
    accentText: "#FFFFFF",
    ctaColor: "#BE185D",
    ctaText: "#FFFFFF",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    layout: "diagonal-cut",
  },
  // 14 — Slate Professional
  {
    id: "slate-pro",
    name: "Slate Professional",
    description: "Clean corporate style — serious and effective",
    previewColor: "bg-slate-600",
    bgColor: "#F8FAFC",
    bgAccent: "#E2E8F0",
    headerColor: "#475569",
    headerText: "#FFFFFF",
    bodyText: "#1E293B",
    accentColor: "#64748B",
    accentText: "#FFFFFF",
    ctaColor: "#0EA5E9",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "sidebar-info",
  },
  // 15 — Candy Pop
  {
    id: "candy-pop",
    name: "Candy Pop",
    description: "Fun, vibrant multicolor design for family-friendly appeal",
    previewColor: "bg-fuchsia-500",
    bgColor: "#FDF4FF",
    bgAccent: "#F5D0FE",
    headerColor: "#A21CAF",
    headerText: "#FFFFFF",
    bodyText: "#701A75",
    accentColor: "#D946EF",
    accentText: "#FFFFFF",
    ctaColor: "#A21CAF",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "centered-photo",
  },
  // 16 — Earth Tone
  {
    id: "earth-tone",
    name: "Earth Tone",
    description: "Natural earthy colors — grounded and sincere",
    previewColor: "bg-stone-500",
    bgColor: "#FAFAF9",
    bgAccent: "#D6D3D1",
    headerColor: "#78716C",
    headerText: "#FAFAF9",
    bodyText: "#292524",
    accentColor: "#A8A29E",
    accentText: "#292524",
    ctaColor: "#57534E",
    ctaText: "#FAFAF9",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    layout: "minimal-clean",
  },
  // 17 — Cherry Emergency
  {
    id: "cherry-emergency",
    name: "Cherry Emergency",
    description: "Urgent high-alert design with bold cherry red accents",
    previewColor: "bg-red-700",
    bgColor: "#FEF2F2",
    bgAccent: "#FECACA",
    headerColor: "#B91C1C",
    headerText: "#FFFFFF",
    bodyText: "#7F1D1D",
    accentColor: "#EF4444",
    accentText: "#FFFFFF",
    ctaColor: "#B91C1C",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "photo-dominant",
  },
  // 18 — Sky Breeze
  {
    id: "sky-breeze",
    name: "Sky Breeze",
    description: "Light and airy sky blue — hopeful and inviting",
    previewColor: "bg-sky-400",
    bgColor: "#F0F9FF",
    bgAccent: "#BAE6FD",
    headerColor: "#0284C7",
    headerText: "#FFFFFF",
    bodyText: "#0C4A6E",
    accentColor: "#38BDF8",
    accentText: "#0C4A6E",
    ctaColor: "#0284C7",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "editorial",
  },
  // 19 — Charcoal & Gold
  {
    id: "charcoal-gold",
    name: "Charcoal & Gold",
    description: "Premium dark charcoal with gold accents — luxury feel",
    previewColor: "bg-zinc-800",
    bgColor: "#27272A",
    bgAccent: "#3F3F46",
    headerColor: "#EAB308",
    headerText: "#27272A",
    bodyText: "#E4E4E7",
    accentColor: "#EAB308",
    accentText: "#27272A",
    ctaColor: "#EAB308",
    ctaText: "#27272A",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    layout: "retro-badge",
  },
  // 20 — Lavender Dream
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    description: "Soft lavender with gentle purple accents — calming and kind",
    previewColor: "bg-violet-400",
    bgColor: "#F5F3FF",
    bgAccent: "#DDD6FE",
    headerColor: "#7C3AED",
    headerText: "#FFFFFF",
    bodyText: "#4C1D95",
    accentColor: "#8B5CF6",
    accentText: "#FFFFFF",
    ctaColor: "#7C3AED",
    ctaText: "#FFFFFF",
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    layout: "diagonal-cut",
  },
];
