import jsPDF from "jspdf";

interface FlyerData {
  petName: string;
  species: string;
  breed: string;
  color?: string;
  description?: string;
  lastSeenAddress?: string;
  reward?: string;
  contactPhone?: string;
  petId: string;
  imageUrl?: string;
}

export const generateLostFlyer = async (data: FlyerData) => {
  const doc = new jsPDF("p", "mm", "a4");
  const pageW = 210;

  // Red header
  doc.setFillColor(220, 38, 38);
  doc.rect(0, 0, pageW, 45, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  doc.text("LOST PET", pageW / 2, 22, { align: "center" });
  doc.setFontSize(14);
  doc.text("PLEASE HELP US FIND OUR PET!", pageW / 2, 35, { align: "center" });

  // Try to add pet image
  let yPos = 55;
  if (data.imageUrl) {
    try {
      const img = await loadImage(data.imageUrl);
      const imgW = 80;
      const imgH = 80;
      doc.addImage(img, "JPEG", (pageW - imgW) / 2, yPos, imgW, imgH);
      yPos += imgH + 10;
    } catch {
      yPos += 5;
    }
  }

  // Pet details
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text(data.petName.toUpperCase(), pageW / 2, yPos, { align: "center" });
  yPos += 12;

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  const details = [
    `Species: ${data.species}`,
    data.breed ? `Breed: ${data.breed}` : null,
    data.color ? `Color: ${data.color}` : null,
  ].filter(Boolean);
  details.forEach((d) => {
    doc.text(d!, pageW / 2, yPos, { align: "center" });
    yPos += 8;
  });

  if (data.description) {
    yPos += 4;
    doc.setFontSize(12);
    const lines = doc.splitTextToSize(data.description, 160);
    doc.text(lines, pageW / 2, yPos, { align: "center" });
    yPos += lines.length * 6 + 4;
  }

  // Last seen
  if (data.lastSeenAddress) {
    yPos += 4;
    doc.setFillColor(254, 243, 199);
    doc.roundedRect(25, yPos - 6, 160, 16, 3, 3, "F");
    doc.setTextColor(146, 64, 14);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`📍 Last Seen: ${data.lastSeenAddress}`, pageW / 2, yPos + 4, { align: "center" });
    yPos += 20;
  }

  // Reward
  if (data.reward) {
    doc.setFillColor(220, 252, 231);
    doc.roundedRect(40, yPos - 4, 130, 16, 3, 3, "F");
    doc.setTextColor(22, 101, 52);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(`💰 REWARD: ${data.reward}`, pageW / 2, yPos + 6, { align: "center" });
    yPos += 24;
  }

  // Contact
  if (data.contactPhone) {
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`📞 Contact: ${data.contactPhone}`, pageW / 2, yPos + 4, { align: "center" });
    yPos += 16;
  }

  // QR Code section
  yPos = Math.max(yPos, 230);
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(25, yPos - 4, 160, 36, 3, 3, "F");
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Scan the QR code on the pet's tag or visit:", pageW / 2, yPos + 6, { align: "center" });
  doc.setTextColor(0, 100, 150);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(`${window.location.origin}/pet/${data.petId}`, pageW / 2, yPos + 16, { align: "center" });
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Pet ID: ${data.petId.slice(0, 8).toUpperCase()}`, pageW / 2, yPos + 26, { align: "center" });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by PetsRegistry.org", pageW / 2, 290, { align: "center" });

  doc.save(`Lost-${data.petName}-Flyer.pdf`);
};

const loadImage = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      canvas.getContext("2d")?.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/jpeg", 0.8));
    };
    img.onerror = reject;
    img.src = url;
  });
};
